### ISSUE TITLE
Make it easier to run the BDD tests across all the generators

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#10]
It's great to have a single set of tests that ensure generators are spec compliant, however, at the moment if you update the tests you have to execute them separately for each generator.

It would be really cool to be able to update or add tests then run them across every generator, providing a matrix of results. Also, there may be times where some generators lag behind in terms of functionality. This would provide a clear way of illustrating that.

**Comment by jhowlett-scottlogic** [comment]
Proposed solution:

- Add language specific generators as dependencies (with a commit SHA for now) 

- Add command `openapi-forge test-generators` which will loop through all the language specific generators and run BDD tests (tests conducted on command `npm test`).

- report tests results in a table on the CL.

-

**Comment by jhowlett-scottlogic** [comment]
To test the language specific generators i need a local version. To do this i could either add them as NPM dependencies to openapi-forge however that would create circular dependencies because the language specific generators have openapi-forge as a dependency for testing. 

To prevent these circular NPM module dependencies i have chosen to clone git repos of the language specific generators and then use that file path which will also allow for an easy way to give a file path to use a local modified language specific generator which would be useful when both openapi-forge and the language specific generators need to be edited and testing completed on them.

We eventually want to publish NPM modules and i wonder how we will be able to use these NPM modules without circular dependencies?

**Comment by jhowlett-scottlogic** [comment]
@ColinEberhardt I have started working on this, can you can assign it to me please.
