### ISSUE TITLE
integrate JS generator into forge

### ISSUE THREAD

**Issue by jhowlett-scottlogic** [ScottLogic/openapi-forge#140]
- add to test-generators command
- add to README.md

**Comment by ColinEberhardt** [comment]
Looking at the test code a couple of things spring to mind ...

- Rather than parsing the test output, we could use one of the more machine-readable formatters (https://github.com/cucumber/messages), however, I've spotted this isn't supported by the C# implementation (perhaps we should contribute!)
- It would be good if we didn't have to update this project each time a new generator is added.

**Comment by jhowlett-scottlogic** [comment]
i agree, it is not the best. Maybe creating our own standard JSON format that is passed back at the end of testing from each generator with results and failing scenario titles would be enough to create a process where the forge only needs a reference to the npm package to start testing a new generator
