### ISSUE TITLE
Outline how to test generators in the documentation

### ISSUE THREAD

**Issue by Joe-Dunleavy** [ScottLogic/openapi-forge#50]
- steps for testing generators need to be added to the documentation

**Comment by jhowlett-scottlogic** [comment]
Testing fails due to openapi-forge dependency not staying up to date. It takes the version of openapi-forge that was live at the time of adding to the package.json file. 

This version of openapi-forge doesn't handle handlebars partials. 

If you set to most recent verson my changes to openapi-forge causes tests to fail and i am currently working on fixing this.

As a temporary fix delete node_modules and set dependency to  `    "openapi-forge": "github:ColinEberhardt/openapi-forge#b63d843c5026766589e0abc5640f52455bba90fe",` in package.json then run `npm install` to get a passing system.
